[project]
name = "textual-todos"
version = "0.1.0"
description = "A simple todo list app for the terminal built with Textual."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "textual>=3.2.0",
    "textual-dev>=1.7.0",
]
